# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#   desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  pre = "<i class='fa fa-home'></i>  "
#  name = "Home"
#  url = "/#1-hero"
#  weight = 10

[[main]]
  name = "About FORRT"  # A link title for your page.
  url = ""  # The URL of your page.
  weight = 10  # The position of your page in the menu.
  identifier = "about"

[[main]]
  name = "About FORRT"  # A link title for your page.
  url = "/about/us"  # The URL of your page.
  weight = 11  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Awards"  # A link title for your page.
  url = "/awards"  # The URL of your page.
  weight = 12  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Calendar"  # A link title for your page.
  url = "/about/get-involved/#calendar"  # The URL of your page.
  weight = 13  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Code of Conduct"  # A link title for your page.
  url = "/coc"  # The URL of your page.
  weight = 14  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Community"  # A link title for your page.
  url = "/about/community"  # The URL of your page.
  weight = 15  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Contributors"  # A link title for your page.
  url = "/contributors"  # The URL of your page.
  weight = 15  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Curriculum Vitae"  # A link title for your page.
  url = "/cv"  # The URL of your page.
  weight = 15  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Feedback"  # A link title for your page.
  url = "/feedback"  # The URL of your page.
  weight = 15  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Get Involved"  # A link title for your page.
  url = "/about/get-involved"  # The URL of your page.
  weight = 16  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Mission & Advocacy"  # A link title for your page.
  url = "about/mission/"  # The URL of your page.
  weight = 17  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Principles"  # A link title for your page.
  url = "/about/principles/"  # The URL of your page.
  weight = 18  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Partners"  # A link title for your page.
  url = "about/partnerships/"  # The URL of your page.
  weight = 19  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Principles"  # A link title for your page.
  url = "/about/principles/"  # The URL of your page.
  weight = 20  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Talks"  # A link title for your page.
  url = "talk/"  # The URL of your page.
  weight = 21  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Teams"  # A link title for your page.
  url = "about/teams/"  # The URL of your page.
  weight = 22  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Newsletters"  # A link title for your page.
  url = "/newsletters"  # The URL of your page.
  weight = 23  # The position of your page in the menu.
  parent = "about"





[[main]]
  name = "Educational NEXUS"
  url = "/nexus"
  weight = 30
  identifier = "nexus"

[[main]]
  name = "About Educational Nexus"
  url = "/nexus"
  weight = 31
  parent = "nexus"

[[main]]
  name = "Adopting Principled Education"  # A link title for your page.
  url = "/adopting"  # The URL of your page.
  weight = 32  # The position of your page in the menu.
  parent = "nexus"

[[main]]
  name = "Clusters"
  url = "/clusters"
  weight = 33
  parent = "nexus"

[[main]]
  name = "Curated Resources"
  url = "/resources"
  weight = 34
  parent = "nexus"

[[main]]
  name = "Equity in Open Science"
  url = "/equityinos"
  weight = 35
  parent = "nexus"

[[main]]
  name = "Educators' Corner"
  url = "/educators-corner"
  weight = 35
  parent = "nexus"

[[main]]
  name = "Glossary"
  url = "/glossary"
  weight = 36
  parent = "nexus"

[[main]]
  name = "Impact of O&R on students"
  url = "/impact"
  weight = 37
  parent = "nexus"

[[main]]
  name = "Initiatives Towards Social Justice"
  url = "/dei"
  weight = 37
  parent = "nexus"

[[main]]
  name = "Lesson Plans"
  url = "/lesson-plans"
  weight = 38
  parent = "nexus"

[[main]]
  name = "Neurodiversity"
  url = "/neurodiversity"
  weight = 39
  parent = "nexus"

[[main]]
  name = "Pedagogies"
  url = "/pedagogies/"
  weight = 41
  identifier = "pedagogies"

[[main]]
  name = "Self-Assessment"
  url = "/self-assessment"
  weight = 42
  parent = "nexus"

[[main]]
  name = "Summaries"
  url = "/summaries"
  weight = 43
  parent = "nexus"

[[main]]
  name = "Syllabus"
  url = "/syllabus"
  weight = 44
  parent = "nexus"



[[main]]
  name = "Replication Hub"
  url = "/replication-hub"
  weight = 50
  parent = "nexus"

[[main]]
  name = "About Replication Hub"
  url = "/replication-hub"
  weight = 51
  parent = "nexus"

[[main]]
  name = "Replications & Reversals"
  url = "/reversals"
  weight = 52
  parent = "nexus"

[[main]]
  name = "Positive Changes from the Replication Crisis"
  url = "/positive-changes-replication-crisis"
  weight = 53
  parent = "nexus"


[[main]]
  name = "Publications"
  url = "/publications/"
  weight = 70
  identifier = "publications"



# [[main]]
#   name = "Public"
#   url = "/pedagogies/public/"
#   weight = 41
#   parent = "pedagogies"
# [[main]]
#   name = "Undergraduate"
#   url = "/pedagogies/undergraduate/"
#   weight = 42
#   parent = "pedagogies"
# [[main]]
#   name = "Graduate"
#   url = "/pedagogies/graduate"
#   weight = 43
#   parent = "pedagogies"
