# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#   desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  pre = "<i class='fa fa-home'></i>  "
#  name = "Home"
#  url = "/#1-hero"
#  weight = 10

[[main]]
  name = "About FORRT"  # A link title for your page.
  url = ""  # The URL of your page.
  weight = 10  # The position of your page in the menu.
  identifier = "about"

[[main]]
  name = "About FORRT"  # A link title for your page.
  url = "/about/us"  # The URL of your page.
  weight = 11  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Awards"  # A link title for your page.
  url = "/awards"  # The URL of your page.
  weight = 12  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Calendar"  # A link title for your page.
  url = "/about/get-involved/#calendar"  # The URL of your page.
  weight = 13  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Cite us"  # A link title for your page.
  url = "about/cite_us/"  # The URL of your page.
  weight = 14  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Charity"  # A link title for your page.
  url = "about/charity/"  # The URL of your page.
  weight = 15  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Code of Conduct"  # A link title for your page.
  url = "/coc"  # The URL of your page.
  weight = 16  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Community"  # A link title for your page.
  url = "/about/community"  # The URL of your page.
  weight = 17  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Community Map"  # A link title for your page.
  url = "/community-map"  # The URL of your page.
  weight = 18  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Contributors"  # A link title for your page.
  url = "/contributors"  # The URL of your page.
  weight = 19  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Curriculum Vitae"  # A link title for your page.
  url = "/cv"  # The URL of your page.
  weight = 20  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Feedback"  # A link title for your page.
  url = "/feedback"  # The URL of your page.
  weight = 21  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Get Involved"  # A link title for your page.
  url = "/about/get-involved"  # The URL of your page.
  weight = 22  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Mission & Advocacy"  # A link title for your page.
  url = "about/mission/"  # The URL of your page.
  weight = 23  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Newsletters"  # A link title for your page.
  url = "/newsletters"  # The URL of your page.
  weight = 24  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Partners"  # A link title for your page.
  url = "about/partnerships/"  # The URL of your page.
  weight = 25  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Principles"  # A link title for your page.
  url = "/about/principles/"  # The URL of your page.
  weight = 26  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Steering Committee"  # A link title for your page.
  url = "/about/steering-committee/"  # The URL of your page.
  weight = 27  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Teams"  # A link title for your page.
  url = "about/teams/"  # The URL of your page.
  weight = 29  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Testimonials"  # A link title for your page.
  url = "/testimonials/"  # The URL of your page.
  weight = 30  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Visitors"  # A link title for your page.
  url = "/about/visitors"  # The URL of your page.
  weight = 31  # The position of your page in the menu.
  parent = "about"


[[main]]
  name = "Educational NEXUS"
  url = "/nexus"
  weight = 30
  identifier = "nexus"

  [[main]]
    name = "About Educational Nexus"
    url = "/nexus"
    weight = 31
    parent = "nexus"

  [[main]]
    name = "Adopting Principled Education"
    url = "/adopting"
    weight = 32
    parent = "nexus"

  [[main]]
    name = "Citation Politics"
    url = "/citation-politics"
    weight = 33
    parent = "nexus"

  [[main]]
    name = "Clusters"
    url = "/clusters"
    weight = 34
    parent = "nexus"

  [[main]]
    name = "Curated Resources"
    url = "/resources"
    weight = 35
    parent = "nexus"

  [[main]]
    name = "Developing Countries & OS"
    url = "/os-developing-world"
    weight = 36
    parent = "nexus"

  [[main]]
    name = "Educators' Corner"
    url = "/educators-corner"
    weight = 37
    parent = "nexus"

  [[main]]
    name = "Equity in Open Science"
    url = "/equityinos"
    weight = 38
    parent = "nexus"

  [[main]]
    name = "Games Portal"
    url = "/games"
  # url = "https://forrt.org/apps/open_research_games_portal.html"
    weight = 39
    parent = "nexus"

  [[main]]
    name = "Glossary"
    url = "/glossary"
    weight = 40
    parent = "nexus"

  [[main]]
    name = "Impact of OS on students"
    url = "/impact"
    weight = 41
    parent = "nexus"

  [[main]]
    name = "Lesson Plans"
    url = "/lesson-plans/"
    weight = 42
    parent = "nexus"

  [[main]]
    name = "Mapping OS Communities"
    url = "/mapping_os"
    weight = 43
    parent = "nexus"

  [[main]]
    name = "Neurodiversity Team"
    url = "/neurodiversity"
    weight = 44
    parent = "nexus"

  [[main]]
    name = "Pedagogies"
    url = "/pedagogies"
    weight = 45
    parent = "nexus"

  [[main]]
    name = "Social Justice Initiatives"
    url = "/dei"
    weight = 47
    parent = "nexus"

  [[main]]
    name = "Summaries"
    url = "/summaries"
    weight = 48
    parent = "nexus"

  [[main]]
    name = "Syllabi Collection"
    url = "/syllabus"
    weight = 49
    parent = "nexus"

  [[main]]
    name = "Teaching OS"
    url = "/teaching_os"
    weight = 50
    parent = "nexus"

  [[main]]
    name = "Wheel of Privilege"
    url = "/awop"
    weight = 51
    parent = "nexus"


[[main]]
  name = "Replication Hub"
  url = "/replication-hub"
  weight = 60
  identifier = "replications"

[[main]]
  name = "About Replication Hub"
  url = "/replication-hub"
  weight = 61
  parent = "replications"

[[main]]
  name = "FLoRA Annotator"
  url = "https://forrt.org/annotator"
  weight = 62
  parent = "replications"

[[main]]
  name = "FReD Explorer"
  url = "https://forrt.org/explorer"
  weight = 63
  parent = "replications"

[[main]]
  name = "FReD R-Package"
  url = "https://forrt.org/FReD/index.html"
  weight = 64
  parent = "replications"

[[main]]
  name = "Handbook for Reproductions and Replications"
  url = "https://forrt.org/replication_handbook/"
  weight = 65
  parent = "replications"

[[main]]
  name = "Large-Scale Replication Projects"
  url = "/replication-hub/large-scale-replication-projects"
  weight = 66
  parent = "replications"

#[[main]]
#  name = "Open Social Psychology by Rima-Maria Rahal"
#  url = "https://forrt.org/open-social-psychology/"
#  weight = 67
#  parent = "replications"

[[main]]
  name = "Positive Changes from the Replication Crisis"
  url = "/positive-changes-replication-crisis"
  weight = 68
  parent = "replications"

[[main]]
  name = "Replications & Reversals"
  url = "/reversals"
  weight = 69
  parent = "replications"

[[main]]
  name = "Replication Research Journal"
  url = "https://replicationresearch.org"
  weight = 70
  parent = "replications"

[[main]]
  name = "Replication Manuscript Templates"
  url = "https://osf.io/brxtd/"
  weight = 71
  parent = "replications"

[[main]]
  name = "Submit a replication to FReD"
  url = "/replication-hub/submit"
  weight = 72
  parent = "replications"


[[main]]
  name = "Publications"
  url = "/publications/"
  weight = 80
  identifier = "publications"
