# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#   desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  pre = "<i class='fa fa-home'></i>  "
#  name = "Home"
#  url = "/#1-hero"
#  weight = 10

[[main]]
  name = "About FORRT"  # A link title for your page.
  url = ""  # The URL of your page.
  weight = 10  # The position of your page in the menu.
  identifier = "about"

[[main]]
  name = "About us"  # A link title for your page.
  url = "/about/us"  # The URL of your page.
  weight = 11  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Awards"  # A link title for your page.
  url = "/awards"  # The URL of your page.
  weight = 12  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Code of Conduct"  # A link title for your page.
  url = "/coc"  # The URL of your page.
  weight = 13  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Get Involved"  # A link title for your page.
  url = "/about/get-involved"  # The URL of your page.
  weight = 14  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Mission & Advocacy"  # A link title for your page.
  url = "about/mission/"  # The URL of your page.
  weight = 15  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Our Calendar"  # A link title for your page.
  url = "/about/get-involved/#calendar"  # The URL of your page.
  weight = 16  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Our Community"  # A link title for your page.
  url = "/about/community"  # The URL of your page.
  weight = 17  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Our Manuscript"  # A link title for your page.
  url = "/manuscript/"  # The URL of your page.
  weight = 18  # The position of your page in the menu.
  parent = "about"

[[main]]
  name = "Principles"  # A link title for your page.
  url = "/about/principles/"  # The URL of your page.
  weight = 19  # The position of your page in the menu.
  parent = "about"






[[main]]
  name = "Educational NEXUS"
  url = "/nexus"
  weight = 30
  identifier = "nexus"

[[main]]
  name = "About Educational Nexus"
  url = "/nexus"
  weight = 31
  parent = "nexus"

[[main]]
  name = "Adopting Principled Education"  # A link title for your page.
  url = "/adopting"  # The URL of your page.
  weight = 32  # The position of your page in the menu.
  parent = "nexus"

[[main]]
  name = "Clusters"
  url = "/clusters"
  weight = 33
  parent = "nexus"

[[main]]
  name = "Curated Resources"
  url = "/resources"
  weight = 34
  parent = "nexus"


[[main]]
  name = "Educators' Corner"
  url = "/educators-corner"
  weight = 35
  parent = "nexus"

[[main]]
  name = "Glossary"
  url = "/glossary"
  weight = 36
  parent = "nexus"

[[main]]
  name = "Initiatives Towards Social Justice"
  url = "/dei"
  weight = 37
  parent = "nexus"

[[main]]
  name = "Lesson Plans"
  url = "/lesson-plans"
  weight = 38
  parent = "nexus"

[[main]]
  name = "Reversals & Replications"
  url = "/reversals"
  weight = 39
  parent = "nexus"

[[main]]
  name = "Self-Assessment"
  url = "/self-assessment"
  weight = 40
  parent = "nexus"

[[main]]
  name = "Summaries"
  url = "/summaries"
  weight = 41
  parent = "nexus"

[[main]]
  name = "Syllabus"
  url = "/syllabus"
  weight = 42
  parent = "nexus"


[[main]]
  name = "Pedagogies"
  url = "/pedagogies/"
  weight = 50
  identifier = "pedagogies"


[[main]]
  name = "Publications"
  url = "/publications/"
  weight = 70
  identifier = "publications"

  

# [[main]]
#   name = "Public"
#   url = "/pedagogies/public/"
#   weight = 41
#   parent = "pedagogies"
# [[main]]
#   name = "Undergraduate"
#   url = "/pedagogies/undergraduate/"
#   weight = 42
#   parent = "pedagogies"
# [[main]]
#   name = "Graduate"
#   url = "/pedagogies/graduate"
#   weight = 43
#   parent = "pedagogies"
